'use client';

import { useState } from 'react';
import { SavedMealPlanWithFoods, CatFood } from '@/types';
import { getKcalPerUnit } from '@/lib/nutrition';

interface SavedPlanPDFButtonProps {
  plan: SavedMealPlanWithFoods;
  disabled?: boolean;
}

export default function SavedPlanPDFButton({
  plan,
  disabled,
}: SavedPlanPDFButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const handleDownload = async (e: React.MouseEvent) => {
    e.stopPropagation();
    if (disabled || isGenerating) return;

    setIsGenerating(true);
    try {
      // Dynamic import jspdf for simpler PDF generation
      const { jsPDF } = await import('jspdf');

      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();

      // Header
      doc.setFontSize(24);
      doc.setTextColor(249, 115, 22); // Orange
      doc.text('MealMeow', pageWidth / 2, 20, { align: 'center' });

      doc.setFontSize(12);
      doc.setTextColor(107, 114, 128); // Gray
      doc.text('Meal Plan', pageWidth / 2, 28, { align: 'center' });

      // Plan Name
      doc.setFontSize(18);
      doc.setTextColor(17, 24, 39); // Dark gray
      doc.text(plan.plan_name, pageWidth / 2, 45, { align: 'center' });

      // Nutrition Info Box
      doc.setFillColor(249, 250, 251); // Light gray background
      doc.roundedRect(20, 55, pageWidth - 40, 25, 3, 3, 'F');

      doc.setFontSize(11);
      doc.setTextColor(107, 114, 128);
      doc.text('Target Calories', 30, 65);
      doc.text('Meals per Day', pageWidth / 2, 65);
      doc.text('Est. Monthly Cost', pageWidth - 50, 65);

      doc.setFontSize(14);
      doc.setTextColor(17, 24, 39);
      doc.text(`${plan.target_der} kcal`, 30, 73);
      doc.text(`${plan.meals_per_day}x`, pageWidth / 2, 73);
      doc.text(`$${(plan.total_monthly_cost || 0).toFixed(2)}`, pageWidth - 50, 73);

      // Foods Section
      doc.setFontSize(14);
      doc.setTextColor(17, 24, 39);
      doc.text('Foods in This Plan', 20, 95);

      let yPos = 105;
      const foodMap = new Map<string, CatFood>();
      plan.foods.forEach(food => foodMap.set(food.id, food));

      plan.food_selections.forEach((selection, index) => {
        const food = foodMap.get(selection.foodId);
        if (!food) return;

        const { kcal, unit } = getKcalPerUnit(food);
        const totalMeals = plan.food_selections.reduce((sum, s) => sum + s.mealCount, 0);
        const calorieShare = (selection.mealCount / totalMeals) * plan.target_der;
        const dailyAmount = kcal > 0 ? calorieShare / kcal : 0;
        const amountPerMeal = selection.mealCount > 0 ? dailyAmount / selection.mealCount : 0;

        // Food background
        const bgColor = index === 0 ? [255, 237, 213] : [219, 234, 254]; // Orange-50 or Blue-50
        doc.setFillColor(bgColor[0], bgColor[1], bgColor[2]);
        doc.roundedRect(20, yPos - 5, pageWidth - 40, 22, 2, 2, 'F');

        // Food name
        doc.setFontSize(12);
        doc.setTextColor(17, 24, 39);
        doc.text(`${food.brand} ${food.product_name}`, 25, yPos + 3);

        // Amount
        doc.setFontSize(10);
        doc.setTextColor(107, 114, 128);
        doc.text(`${amountPerMeal.toFixed(2)} ${unit}(s) per meal`, 25, yPos + 11);

        // Meal count
        doc.text(`${selection.mealCount} meal(s)/day`, pageWidth - 50, yPos + 7);

        yPos += 28;
      });

      // Derived from info (if available)
      if (plan.derived_from_weight_lbs || plan.derived_from_age_months) {
        yPos += 10;
        doc.setFontSize(10);
        doc.setTextColor(107, 114, 128);
        let derivedText = 'Calculated for: ';
        if (plan.derived_from_weight_lbs) {
          derivedText += `${plan.derived_from_weight_lbs} lbs`;
        }
        if (plan.derived_from_age_months) {
          const years = Math.floor(plan.derived_from_age_months / 12);
          const months = plan.derived_from_age_months % 12;
          derivedText += plan.derived_from_weight_lbs ? ', ' : '';
          if (years > 0) {
            derivedText += `${years} year${years !== 1 ? 's' : ''}`;
          }
          if (months > 0) {
            derivedText += years > 0 ? ` ${months} mo` : `${months} months`;
          }
        }
        doc.text(derivedText, 20, yPos);
      }

      // Footer
      doc.setFontSize(9);
      doc.setTextColor(156, 163, 175);
      doc.text(
        `Generated by MealMeow on ${new Date().toLocaleDateString()}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 15,
        { align: 'center' }
      );

      // Save
      const fileName = `${plan.plan_name.replace(/[^a-zA-Z0-9]/g, '_')}_meal_plan.pdf`;
      doc.save(fileName);
    } catch (error) {
      console.error('PDF generation failed:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <button
      type="button"
      disabled={disabled || isGenerating}
      onClick={handleDownload}
      className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${
        disabled || isGenerating
          ? 'bg-gray-100 text-gray-400 cursor-not-allowed opacity-50'
          : 'bg-gray-100 text-gray-600 hover:bg-gray-200'
      }`}
      title="Download meal plan as PDF"
    >
      {isGenerating ? (
        <>
          <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
            <circle
              className="opacity-25"
              cx="12"
              cy="12"
              r="10"
              stroke="currentColor"
              strokeWidth="4"
            />
            <path
              className="opacity-75"
              fill="currentColor"
              d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
            />
          </svg>
          <span>...</span>
        </>
      ) : (
        <>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
            />
          </svg>
          <span>PDF</span>
        </>
      )}
    </button>
  );
}
