export const CAT_BREEDS = [
  'Domestic Shorthair',
  'Domestic Longhair',
  'Domestic Medium Hair',
  'Abyssinian',
  'American Bobtail',
  'American Curl',
  'American Shorthair',
  'American Wirehair',
  'Balinese',
  'Bengal',
  'Birman',
  'Bombay',
  'British Shorthair',
  'Burmese',
  'Burmilla',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Egyptian Mau',
  'Exotic Shorthair',
  'Havana Brown',
  'Himalayan',
  'Japanese Bobtail',
  'Javanese',
  'Korat',
  'LaPerm',
  'Maine Coon',
  'Manx',
  'Munchkin',
  'Norwegian Forest Cat',
  'Ocicat',
  'Oriental',
  'Persian',
  'Ragamuffin',
  'Ragdoll',
  'Russian Blue',
  'Savannah',
  'Scottish Fold',
  'Selkirk Rex',
  'Siamese',
  'Siberian',
  'Singapura',
  'Snowshoe',
  'Somali',
  'Sphynx',
  'Tonkinese',
  'Turkish Angora',
  'Turkish Van',
  'Mixed Breed',
  'Unknown',
] as const;

export const ACTIVITY_LEVELS = [
  { value: 'inactive', label: 'Inactive / Indoor only' },
  { value: 'normal', label: 'Normal activity' },
  { value: 'active', label: 'Very active / Outdoor access' },
] as const;

export const GOALS = [
  { value: 'maintain', label: 'Maintain weight' },
  { value: 'lose', label: 'Lose weight' },
  { value: 'gain', label: 'Gain weight' },
] as const;

export const FOOD_TYPES = [
  { value: 'any', label: 'Any type' },
  { value: 'dry', label: 'Dry food only' },
  { value: 'wet', label: 'Wet food only' },
] as const;

export const SPECIAL_BENEFITS = [
  'Hairball Control',
  'Weight Management',
  'Urinary Health',
  'Sensitive Stomach',
  'Dental Health',
  'Skin & Coat',
  'Joint Support',
  'Indoor Formula',
  'High Protein',
  'Grain Free',
] as const;
