-- Seed file: Import food data from MealData-Jan28-final.xlsx
-- Run this in the Supabase SQL Editor after running the migration
-- WARNING: This will DELETE all existing foods and replace them with new data

-- Clear existing foods (this will cascade to recommendation_feedback if foreign keys exist)
DELETE FROM cat_foods;

-- Insert new foods from Jan 28 data
INSERT INTO cat_foods (
  brand,
  product_name,
  food_type,
  flavour,
  life_stage,
  kcal_per_cup,
  kcal_per_can,
  can_size_oz,
  price_per_unit,
  unit_size,
  servings_per_unit,
  protein_pct,
  fat_pct,
  fiber_pct,
  moisture_pct,
  special_benefits,
  is_complete_balanced,
  image_url,
  purchase_url
) VALUES
-- Fancy Feast Gravy Lovers Poultry & Beef Feast Variety Pack - Turkey Feast
(
  'Fancy Feast',
  'Gravy Lovers Poultry & Beef Feast Variety Pack Canned Cat Food',
  'wet',
  'Turkey Feast',
  'all',
  NULL,
  65,
  3,
  0.32,
  '24 pack (3 oz cans)',
  24,
  9,
  2,
  1.5,
  82,
  ARRAY['made without artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-gravy-lovers-poultry-beef-feast-variety-pack-canned-cat-food-3oz-case-of-24/img-476200._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-gravy-lovers-poultry-beef/dp/103856'
),
-- Fancy Feast Gravy Lovers Poultry & Beef Feast Variety Pack - Chicken Feast
(
  'Fancy Feast',
  'Gravy Lovers Poultry & Beef Feast Variety Pack Canned Cat Food',
  'wet',
  'Chicken Feast',
  'all',
  NULL,
  67,
  3,
  0.32,
  '24 pack (3 oz cans)',
  24,
  9,
  2,
  1.5,
  82,
  ARRAY['made without artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-gravy-lovers-poultry-beef-feast-variety-pack-canned-cat-food-3oz-case-of-24/img-476200._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-gravy-lovers-poultry-beef/dp/103856'
),
-- Fancy Feast Gravy Lovers Poultry & Beef Feast Variety Pack - Beef Feast
(
  'Fancy Feast',
  'Gravy Lovers Poultry & Beef Feast Variety Pack Canned Cat Food',
  'wet',
  'Beef Feast',
  'all',
  NULL,
  65,
  3,
  0.32,
  '24 pack (3 oz cans)',
  24,
  9,
  2,
  1.5,
  82,
  ARRAY['made without artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-gravy-lovers-poultry-beef-feast-variety-pack-canned-cat-food-3oz-case-of-24/img-476200._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-gravy-lovers-poultry-beef/dp/103856'
),
-- Fancy Feast Classic Seafood Feast Variety Pack - Cod, Sole & Shrimp Feast
(
  'Fancy Feast',
  'Classic Seafood Feast Variety Pack Canned Cat Food',
  'wet',
  'Cod, Sole & Shrimp Feast',
  'all',
  NULL,
  82,
  3,
  0.32,
  '24 pack (3 oz cans)',
  24,
  12,
  2,
  1.5,
  78,
  ARRAY['grain-free', 'no artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-classic-seafood-feast-variety-pack-canned-cat-food-3oz-case-of-24/img-417636._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-classic-seafood-feast/dp/103924'
),
-- Fancy Feast Classic Seafood Feast Variety Pack - Savory Salmon Feast
(
  'Fancy Feast',
  'Classic Seafood Feast Variety Pack Canned Cat Food',
  'wet',
  'Savory Salmon Feast',
  'all',
  NULL,
  88,
  3,
  0.32,
  '24 pack (3 oz cans)',
  24,
  11,
  4,
  1.5,
  78,
  ARRAY['grain-free', 'no artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-classic-seafood-feast-variety-pack-canned-cat-food-3oz-case-of-24/img-417636._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-classic-seafood-feast/dp/103924'
),
-- Fancy Feast Classic Seafood Feast Variety Pack - Ocean Whitefish & Tuna Feast
(
  'Fancy Feast',
  'Classic Seafood Feast Variety Pack Canned Cat Food',
  'wet',
  'Ocean Whitefish & Tuna Feast',
  'all',
  NULL,
  88,
  3,
  0.32,
  '24 pack (3 oz cans)',
  24,
  12,
  2,
  1.5,
  78,
  ARRAY['grain-free', 'no artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-classic-seafood-feast-variety-pack-canned-cat-food-3oz-case-of-24/img-417636._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-classic-seafood-feast/dp/103924'
),
-- Friskies Gravy Variety Pack - Shreds With Beef in Gravy
(
  'Friskies',
  'Gravy Variety Pack Canned Cat Food',
  'wet',
  'Shreds With Beef in Gravy',
  'all',
  NULL,
  130,
  5.5,
  0.16,
  '24 pack (5.5 oz cans)',
  24,
  9,
  2.5,
  1,
  82,
  ARRAY['packed with essential nutrients', 'no artificial colors or preservatives', 'enriched with vitamins minerals and taurine'],
  true,
  'https://image.chewy.com/catalog/general/images/friskies-shreds-in-gravy-variety-pack-canned-cat-food-5-5oz-can-case-of-40/img-510128._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/friskies-shreds-in-gravy-variety-pack/dp/174906'
),
-- Friskies Gravy Variety Pack - Shreds Turkey & Cheese Dinner in Gravy
(
  'Friskies',
  'Gravy Variety Pack Canned Cat Food',
  'wet',
  'Shreds Turkey & Cheese Dinner in Gravy',
  'all',
  NULL,
  129,
  5.5,
  0.16,
  '24 pack (5.5 oz cans)',
  24,
  9,
  2.5,
  1,
  82,
  ARRAY['packed with essential nutrients', 'enriched with vitamins minerals and taurine', 'no artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/friskies-shreds-in-gravy-variety-pack-canned-cat-food-5-5oz-can-case-of-40/img-510128._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/friskies-shreds-in-gravy-variety-pack/dp/174906'
),
-- Friskies Gravy Variety Pack - Shreds With Ocean Whitefish & Tuna in Sauce
(
  'Friskies',
  'Gravy Variety Pack Canned Cat Food',
  'wet',
  'Shreds With Ocean Whitefish & Tuna in Sauce',
  'all',
  NULL,
  128,
  5.5,
  0.17,
  '24 pack (5.5 oz cans)',
  24,
  9,
  2,
  1,
  82,
  ARRAY['packed with essential nutrients', 'enriched with vitamins minerals and taurine', 'no artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/friskies-shreds-in-gravy-variety-pack-canned-cat-food-5-5oz-can-case-of-40/img-510128._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/friskies-shreds-in-gravy-variety-pack/dp/174906'
),
-- Friskies Gravy Variety Pack - Shreds Chicken & Salmon Dinner in Gravy
(
  'Friskies',
  'Gravy Variety Pack Canned Cat Food',
  'wet',
  'Shreds Chicken & Salmon Dinner in Gravy',
  'all',
  NULL,
  130,
  5.5,
  0.16,
  '24 pack (5.5 oz cans)',
  24,
  9,
  2.5,
  1,
  82,
  ARRAY['packed with essential nutrients', 'enriched with vitamins minerals and taurine', 'no artificial colors or preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/friskies-shreds-in-gravy-variety-pack-canned-cat-food-5-5oz-can-case-of-40/img-510128._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/friskies-shreds-in-gravy-variety-pack/dp/174906'
),
-- Fancy Feast Medleys Primavera Collection - White Meat Chicken Primavera
(
  'Fancy Feast',
  'Medleys Primavera Collection Adult Chicken Turkey & Tuna Variety Pack in Broth Gourmet Wet Cat Food',
  'wet',
  'White Meat Chicken Primavera',
  'all',
  NULL,
  67,
  3,
  0.39,
  '24 pack (3 oz cans)',
  24,
  10,
  2,
  1.5,
  82,
  ARRAY['without any artificial colors and preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-medleys-primavera-collection-adult-chicken-turkey-tuna-variety-pack-in-broth-gourmet-wet-cat-food-3oz-case-of-12/img-457836._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-medleys-primavera/dp/104395'
),
-- Fancy Feast Medleys Primavera Collection - Tuna Primavera
(
  'Fancy Feast',
  'Medleys Primavera Collection Adult Chicken Turkey & Tuna Variety Pack in Broth Gourmet Wet Cat Food',
  'wet',
  'Tuna Primavera',
  'all',
  NULL,
  67,
  3,
  0.39,
  '24 pack (3 oz cans)',
  24,
  10,
  2,
  1.5,
  82,
  ARRAY['without any artificial colors and preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-medleys-primavera-collection-adult-chicken-turkey-tuna-variety-pack-in-broth-gourmet-wet-cat-food-3oz-case-of-12/img-457836._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-medleys-primavera/dp/104395'
),
-- Fancy Feast Medleys Primavera Collection - Tender Turkey Primavera
(
  'Fancy Feast',
  'Medleys Primavera Collection Adult Chicken Turkey & Tuna Variety Pack in Broth Gourmet Wet Cat Food',
  'wet',
  'Tender Turkey Primavera',
  'all',
  NULL,
  67,
  3,
  0.39,
  '24 pack (3 oz cans)',
  24,
  10,
  2,
  1.5,
  82,
  ARRAY['without any artificial colors and preservatives'],
  true,
  'https://image.chewy.com/catalog/general/images/fancy-feast-medleys-primavera-collection-adult-chicken-turkey-tuna-variety-pack-in-broth-gourmet-wet-cat-food-3oz-case-of-12/img-457836._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/fancy-feast-medleys-primavera/dp/104395'
),
-- Blue Buffalo Tastefuls Tender Morsels - Chicken Entree
(
  'Blue Buffalo',
  'Tastefuls Tender Morsels Chicken Entree Wet Cat Food',
  'wet',
  'Chicken Entree',
  'adult',
  NULL,
  80,
  3,
  0.42,
  '24 pack (3 oz cans)',
  24,
  9,
  4,
  1.5,
  82,
  ARRAY['high moisture', 'no chicken or poultry by-product meals', 'no corn wheat or soy'],
  true,
  'https://image.chewy.com/catalog/general/images/moe/068c47cd-9c6d-7031-8000-aea8d5d1e8aa._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/blue-buffalo-tastefuls-tender-morsels/dp/3283918'
),
-- Blue Buffalo Tastefuls Tender Morsels - Tuna Entree
(
  'Blue Buffalo',
  'Tastefuls Tender Morsels Tuna Entree Wet Cat Food',
  'wet',
  'Tuna Entree',
  'adult',
  NULL,
  70,
  3,
  0.43,
  '24 pack (3 oz cans)',
  24,
  9,
  2,
  1.5,
  82,
  ARRAY['high moisture', 'no chicken or poultry by-product meals', 'no corn wheat or soy'],
  true,
  'https://image.chewy.com/catalog/general/images/moe/068c47cd-9c6d-7031-8000-aea8d5d1e8aa._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/blue-buffalo-tastefuls-tender-morsels/dp/3283894'
),
-- Royal Canin Feline Health Nutrition Kitten - Thin Slices in Gravy
(
  'Royal Canin',
  'Feline Health Nutrition Kitten Thin Slices in Gravy Wet Cat Food',
  'wet',
  'Thin Slices in Gravy',
  'kitten',
  NULL,
  76,
  3,
  0.77,
  '24 pack (3 oz cans)',
  24,
  10.5,
  2.5,
  1.4,
  80.2,
  ARRAY['blend of antioxidants including vitamins E and C', 'highly digestible proteins fiber and prebiotics'],
  true,
  'https://image.chewy.com/catalog/general/images/royal-canin-feline-health-nutrition-thin-slices-in-gravy-wet-kitten-food-3oz-can-case-of-12/img-316877._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/royal-canin-feline-health-nutrition/dp/127187'
),
-- Royal Canin Feline Health Nutrition Kitten - Loaf in Sauce
(
  'Royal Canin',
  'Feline Health Nutrition Kitten Loaf in Sauce Wet Cat Food',
  'wet',
  'Loaf in Sauce',
  'kitten',
  NULL,
  76,
  3,
  0.77,
  '24 pack (3 oz cans)',
  24,
  10.8,
  3.2,
  1.7,
  80,
  ARRAY['digestible proteins fiber and prebiotics', 'innovative blend of antioxidants'],
  true,
  'https://image.chewy.com/catalog/general/images/royal-canin-feline-health-nutrition-variety-pack-pate-wet-kitten-food-3oz-can-case-of-12/img-271007._AC_SL1200_QL100_V1_.jpg',
  'https://www.chewy.com/royal-canin-feline-health-nutrition/dp/1660518'
);
